// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvgubqqjvmsepkilnkak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2Z3VicXFqdm1zZXBraWxua2FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMTY0OTMsImV4cCI6MjA3MDg5MjQ5M30.tPVV11ccV04rD2mr76zDwW_Xn-b0hAQAaYh7oUpN96I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});